# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='insert_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 17, 13, 6, 307484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
