# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171105_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='insert_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
