# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171105_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='insert_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 17, 34, 38, 409311, tzinfo=utc)),
        ),
    ]
