# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='insert_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='insert_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
